/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.freesr;

public class ArrayListDouble {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayListDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayListDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FreeSpeakerRecognitionJNI.delete_ArrayListDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayListDouble() {
    this(FreeSpeakerRecognitionJNI.new_ArrayListDouble__SWIG_0(), true);
  }

  public ArrayListDouble(long n) {
    this(FreeSpeakerRecognitionJNI.new_ArrayListDouble__SWIG_1(n), true);
  }

  public long size() {
    return FreeSpeakerRecognitionJNI.ArrayListDouble_size(swigCPtr, this);
  }

  public long capacity() {
    return FreeSpeakerRecognitionJNI.ArrayListDouble_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    FreeSpeakerRecognitionJNI.ArrayListDouble_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return FreeSpeakerRecognitionJNI.ArrayListDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    FreeSpeakerRecognitionJNI.ArrayListDouble_clear(swigCPtr, this);
  }

  public void add(double x) {
    FreeSpeakerRecognitionJNI.ArrayListDouble_add(swigCPtr, this, x);
  }

  public double get(int i) {
    return FreeSpeakerRecognitionJNI.ArrayListDouble_get(swigCPtr, this, i);
  }

  public void set(int i, double val) {
    FreeSpeakerRecognitionJNI.ArrayListDouble_set(swigCPtr, this, i, val);
  }

}
