/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.freesr;

public class FreeSpeakerRecognitionJNI {
  public final static native long new_ArrayListDouble__SWIG_0();
  public final static native long new_ArrayListDouble__SWIG_1(long jarg1);
  public final static native long ArrayListDouble_size(long jarg1, ArrayListDouble jarg1_);
  public final static native long ArrayListDouble_capacity(long jarg1, ArrayListDouble jarg1_);
  public final static native void ArrayListDouble_reserve(long jarg1, ArrayListDouble jarg1_, long jarg2);
  public final static native boolean ArrayListDouble_isEmpty(long jarg1, ArrayListDouble jarg1_);
  public final static native void ArrayListDouble_clear(long jarg1, ArrayListDouble jarg1_);
  public final static native void ArrayListDouble_add(long jarg1, ArrayListDouble jarg1_, double jarg2);
  public final static native double ArrayListDouble_get(long jarg1, ArrayListDouble jarg1_, int jarg2);
  public final static native void ArrayListDouble_set(long jarg1, ArrayListDouble jarg1_, int jarg2, double jarg3);
  public final static native void delete_ArrayListDouble(long jarg1);
  public final static native long new_SpeakerGenderRecognizer__SWIG_0(int jarg1);
  public final static native long new_SpeakerGenderRecognizer__SWIG_1();
  public final static native void delete_SpeakerGenderRecognizer(long jarg1);
  public final static native boolean SpeakerGenderRecognizer_Init(long jarg1, SpeakerGenderRecognizer jarg1_);
  public final static native String SpeakerGenderRecognizer_RecognizeSpeakerGender__SWIG_0(long jarg1, SpeakerGenderRecognizer jarg1_, long jarg2, ArrayListDouble jarg2_);
  public final static native String SpeakerGenderRecognizer_RecognizeSpeakerGender__SWIG_1(long jarg1, SpeakerGenderRecognizer jarg1_, String jarg2);
  public final static native double SpeakerGenderRecognizer_GetConfidence(long jarg1, SpeakerGenderRecognizer jarg1_);
  public final static native long new_SpeakerRecognizer__SWIG_0(int jarg1);
  public final static native long new_SpeakerRecognizer__SWIG_1();
  public final static native void delete_SpeakerRecognizer(long jarg1);
  public final static native boolean SpeakerRecognizer_Init(long jarg1, SpeakerRecognizer jarg1_);
  public final static native double SpeakerRecognizer_VerifySpeaker__SWIG_0(long jarg1, SpeakerRecognizer jarg1_, long jarg2, ArrayListDouble jarg2_, long jarg3, ArrayListDouble jarg3_);
  public final static native double SpeakerRecognizer_VerifySpeaker__SWIG_1(long jarg1, SpeakerRecognizer jarg1_, String jarg2, String jarg3);
  public final static native boolean SpeakerRecognizer_RegisterSpeaker__SWIG_0(long jarg1, SpeakerRecognizer jarg1_, long jarg2, ArrayListDouble jarg2_, String jarg3, String jarg4);
  public final static native boolean SpeakerRecognizer_RegisterSpeaker__SWIG_1(long jarg1, SpeakerRecognizer jarg1_, long jarg2, ArrayListDouble jarg2_, String jarg3);
  public final static native boolean SpeakerRecognizer_RegisterSpeaker__SWIG_2(long jarg1, SpeakerRecognizer jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native boolean SpeakerRecognizer_RegisterSpeaker__SWIG_3(long jarg1, SpeakerRecognizer jarg1_, String jarg2, String jarg3);
  public final static native String SpeakerRecognizer_RecognizeSpeaker__SWIG_0(long jarg1, SpeakerRecognizer jarg1_, long jarg2, ArrayListDouble jarg2_);
  public final static native String SpeakerRecognizer_RecognizeSpeaker__SWIG_1(long jarg1, SpeakerRecognizer jarg1_, String jarg2);
  public final static native double SpeakerRecognizer_GetConfidence(long jarg1, SpeakerRecognizer jarg1_);
}
