/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.freesr;

public class SpeakerGenderRecognizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpeakerGenderRecognizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpeakerGenderRecognizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FreeSpeakerRecognitionJNI.delete_SpeakerGenderRecognizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SpeakerGenderRecognizer(int sample_rate) {
    this(FreeSpeakerRecognitionJNI.new_SpeakerGenderRecognizer__SWIG_0(sample_rate), true);
  }

  public SpeakerGenderRecognizer() {
    this(FreeSpeakerRecognitionJNI.new_SpeakerGenderRecognizer__SWIG_1(), true);
  }

  public boolean Init() {
    return FreeSpeakerRecognitionJNI.SpeakerGenderRecognizer_Init(swigCPtr, this);
  }

  public String RecognizeSpeakerGender(ArrayListDouble signal) {
    return FreeSpeakerRecognitionJNI.SpeakerGenderRecognizer_RecognizeSpeakerGender__SWIG_0(swigCPtr, this, ArrayListDouble.getCPtr(signal), signal);
  }

  public String RecognizeSpeakerGender(String fpath) {
    return FreeSpeakerRecognitionJNI.SpeakerGenderRecognizer_RecognizeSpeakerGender__SWIG_1(swigCPtr, this, fpath);
  }

  public double GetConfidence() {
    return FreeSpeakerRecognitionJNI.SpeakerGenderRecognizer_GetConfidence(swigCPtr, this);
  }

}
