/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.freesr;

public class SpeakerRecognizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpeakerRecognizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpeakerRecognizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FreeSpeakerRecognitionJNI.delete_SpeakerRecognizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SpeakerRecognizer(int sample_rate) {
    this(FreeSpeakerRecognitionJNI.new_SpeakerRecognizer__SWIG_0(sample_rate), true);
  }

  public SpeakerRecognizer() {
    this(FreeSpeakerRecognitionJNI.new_SpeakerRecognizer__SWIG_1(), true);
  }

  public boolean Init() {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_Init(swigCPtr, this);
  }

  public double Compare(double[] signal_1, int len_1, double[] signal_2, int len_2) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_Compare__SWIG_0(swigCPtr, this, signal_1, len_1, signal_2, len_2);
  }

  public double Compare(String fpath_1, String fpath_2) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_Compare__SWIG_1(swigCPtr, this, fpath_1, fpath_2);
  }

  public boolean RegisterSpeaker(double[] signal, int len, String id, String model, int update) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_0(swigCPtr, this, signal, len, id, model, update);
  }

  public boolean RegisterSpeaker(double[] signal, int len, String id, String model) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_1(swigCPtr, this, signal, len, id, model);
  }

  public boolean RegisterSpeaker(double[] signal, int len, String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_2(swigCPtr, this, signal, len, id);
  }

  public boolean RegisterSpeaker(String fpath, String id, String model, int update) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_3(swigCPtr, this, fpath, id, model, update);
  }

  public boolean RegisterSpeaker(String fpath, String id, String model) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_4(swigCPtr, this, fpath, id, model);
  }

  public boolean RegisterSpeaker(String fpath, String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_RegisterSpeaker__SWIG_5(swigCPtr, this, fpath, id);
  }

  public RecInfo RecognizeSpeaker(double[] signal, int len) {
    return new RecInfo(FreeSpeakerRecognitionJNI.SpeakerRecognizer_RecognizeSpeaker__SWIG_0(swigCPtr, this, signal, len), true);
  }

  public RecInfo RecognizeSpeaker(String fpath) {
    return new RecInfo(FreeSpeakerRecognitionJNI.SpeakerRecognizer_RecognizeSpeaker__SWIG_1(swigCPtr, this, fpath), true);
  }

  public int FindSpeakerID(String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_FindSpeakerID(swigCPtr, this, id);
  }

  public double VerifySpeaker(double[] signal, int len, String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_VerifySpeaker__SWIG_0(swigCPtr, this, signal, len, id);
  }

  public double VerifySpeaker(String fpath, String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_VerifySpeaker__SWIG_1(swigCPtr, this, fpath, id);
  }

  public boolean DeleteSpeaker(String id) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_DeleteSpeaker(swigCPtr, this, id);
  }

  public boolean LoadSpeaker(String id, String model) {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_LoadSpeaker(swigCPtr, this, id, model);
  }

  public int GetRegisterSpeakerCount() {
    return FreeSpeakerRecognitionJNI.SpeakerRecognizer_GetRegisterSpeakerCount(swigCPtr, this);
  }

}
